<?xml version="1.0" encoding="utf-8"?><Database Name="ScheduleData" Class="ScheduleDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ScheduleData.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ScheduleDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ScheduleResourceData" Member="ScheduleResourceDatas">
    <Type Name="ScheduleResourceData">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CalendarColor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduleEventData" Member="ScheduleEventDatas">
    <Type Name="ScheduleEventData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartTimezone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EndTimezone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsAllDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RecurrenceRule" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RecurrenceID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecurrenceException" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GroupID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>